const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const DEFAULT = 500;
const UNAUTHORISED = 401;
const CONFLICT_ERROR = 409;
const FORBIDDEN_ERROR = 403;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT,
  UNAUTHORISED,
  CONFLICT_ERROR,
  FORBIDDEN_ERROR,
};
